/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class TestSceneUI extends Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":1710,"runtime":"script/GameUI.ts","name":"gameBox","height":1020},"compId":1,"child":[{"type":"Sprite","props":{"y":0,"x":0,"width":1720,"texture":"slot/main_game/back.png","height":1020},"compId":27},{"type":"Animation","props":{"y":322,"x":1378,"width":249,"source":"slot/animations/pers/pers_idle/pers_idle.json","name":"person_idle","height":484,"autoPlay":true},"compId":28},{"type":"Animation","props":{"y":633,"x":277,"source":"slot/animations/fire/fire.json","name":"fire","autoPlay":true},"compId":29}],"loadList":["slot/main_game/back.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(TestSceneUI.uiView);
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}